name: Plugin debug
on:
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:

      - name: Install SVN
        run: sudo apt-get update && sudo apt-get install -y subversion

      - name: Test create and delete SVN tag directory
        run: |
          TAG="test-tag-$(date +%s)"
          echo "Trying to create SVN tag directory: $TAG"
          svn mkdir "https://plugins.svn.wordpress.org/${{ vars.WORDPRESS_ORG_SLUG }}/tags/$TAG" \
            --username "${{ secrets.SVN_USERNAME }}" \
            --password "${{ secrets.SVN_PASSWORD }}" \
            --non-interactive \
            --trust-server-cert \
            -m "Test tag creation"

          echo "Trying to delete SVN tag directory: $TAG"
          svn delete "https://plugins.svn.wordpress.org/${{ vars.WORDPRESS_ORG_SLUG }}/tags/$TAG" \
            --username "${{ secrets.SVN_USERNAME }}" \
            --password "${{ secrets.SVN_PASSWORD }}" \
            --non-interactive \
            --trust-server-cert \
            -m "Remove test tag"
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
